### ISSUE TITLE
/home/perry/data/sbdata/sbdems/shade_merc.tif

### ISSUE THREAD

**Issue by am2222** [perrygeo/archive#1]
Hi,
While searching mapniks xml files I saw a hillshade you have used for shading osm data, can you please share it?or give me some clues to make it? I mean which DEM you have used and if it is possible please share an screen shot of your map with hillshade.
thanks

**Comment by perrygeo** [comment]
That DEM was derived from the USGS National Elevation Dataset, https://nationalmap.gov/elevation.html.

**Comment by am2222** [comment]
@perrygeo thanks for your reply, you have just applied a hillshade?does you worked with different resolutions or you just applied 1 dem?
thanks

**Comment by perrygeo** [comment]
The [`gdaldem hillshade`](http://www.gdal.org/gdaldem.html#gdaldem_hillshade) command was used to create the hillshade from the DEM. Should work for any resolution.

**Comment by am2222** [comment]
@perrygeo  well, thanks very much.
